#!/bin/bash

declare -A color_map=(
    ["FAL"]="\e[38;2;255;3;78m"    # Failure/Error message color
    ["INF"]="\e[94m"               # Information message color
    ["WRN"]="\e[38;5;208m"         # Warning message color
    ["USG"]="\e[0;90m"             # Usage guide message color
    ["RED"]='\e[38;2;25;12;255m'  # Debug Red color
    ["GREEN"]='\e[38;2;3;255;100m' # Green color
    ["BOLD_GREEN_ON_BLACK"]="\033[1;32;40m"
    ["BOLD_GREEN_ON_WHITE"]="\033[1;32;47m"
    ["WHITE_ON_DARK"]="\033[0;37;40m"
    ["BLACK_ON_WHITE"]="\033[0;30;47m"
)
NC='\033[0m' # Reset color

lolnetscan_version="v1"
print_message() {
    local log_level="$1"
    local message="$2"
    local logged_message=$(echo -e "${color_map[$log_level]}[${log_level}]${NC}  ${message}")
    echo "${logged_message}"
}
check_os() {
    local debian_based=("debian" "ubuntu" "linuxmint" "kali")
    local os=$(awk -F= '/^ID=/{print $2}' /etc/os-release)

    if ! [[ " ${debian_based[@]} " =~ " ${os} " ]]; then
        print_message "FAL" "Error: This script is intended for use on Debian-based operating systems (e.g., Debian, Ubuntu, Linux Mint)."
        exit 1
    fi
}

check_dependencies() {
    declare -A dependencies_map=(
    ["nc"]="netcat-openbsd"   # Netcat
    ["shuf"]="coreutils"   # Coreutils
    ["ping"]="iputils-ping" 
)

    local missing_dependencies=()

    for dependency in "${!dependencies_map[@]}"; do
        if ! command -v "$dependency" &>/dev/null; then
            missing_dependencies+=("${dependencies_map[$dependency]}")
        fi
    done

    if [ ${#missing_dependencies[@]} -gt 0 ]; then
        print_message "FAL" "Error: The following dependencies are missing: ${missing_dependencies[*]}"
        print_message "INF" "Please install them using the following command:"
        print_message "USG" "sudo apt-get install ${missing_dependencies[*]}"
        exit 1
    fi
}

print_usage() {
    cat <<EOF
Usage: $0 -host <target> [-p <ports>] [-d] [-u]
Options:
  -host   <target>    Specify the target host(s) using comma, dash, or CIDR notation
  -p      <ports>     Specify the port number(s) using comma or dash
  -u                  Use UDP protocol for port scanning (default is TCP)
EOF
    exit 1
}

validate_ports() {
    local input_ports=("$@")
    local parsed_ports=()

    for port_range in "${input_ports[@]}"; do
        if [[ $port_range == *-* ]]; then
            start_port="${port_range%-*}"
            end_port="${port_range#*-}"

            if ((start_port <= end_port)); then
                for ((port = start_port; port <= end_port; port++)); do
                    parsed_ports+=("$port")
                done
            fi
        else
            parsed_ports+=("$port_range")
        fi
    done
    echo "${parsed_ports[@]}"
}
# Function to extract CIDR IP prefix
extract_cidr_ip_prefix() {
    local cidr_ip="${1%/*}"
    local cidr_prefix="${1#*/}"
    echo "$cidr_ip $cidr_prefix"
}

# Function to convert IP address to an integer
ip_to_int() {
    local ip=$1
    IFS='.' read -r i1 i2 i3 i4 <<< "$ip"
    echo $(( (i1 << 24) + (i2 << 16) + (i3 << 8) + i4 ))
}

# Function to convert an integer to an IP address
int_to_ip() {
    local int_ip=$1
    echo "$(( (int_ip >> 24) & 255 )).$(( (int_ip >> 16) & 255 )).$(( (int_ip >> 8) & 255 )).$(( int_ip & 255 ))"
}

expand_ip_range() {
    IFS=',' read -ra ip_ranges <<< "$1"
    for range in "${ip_ranges[@]}"; do
        if [[ "$range" == *-* ]]; then
            start_ip="${range%-*}"
            end_ip="${range#*-}"

            start_ip_int=$(ip_to_int "$start_ip")
            end_ip_int=$(ip_to_int "$end_ip")

            for ((ip_int = start_ip_int; ip_int <= end_ip_int; ip_int++)); do
                echo "$(int_to_ip "$ip_int")"
            done
        elif [[ "$range" == */* ]]; then
            IFS=' ' read -ra ip_prefix <<< "$(extract_cidr_ip_prefix "$range")"
            local ip="${ip_prefix[0]}"
            local prefix="${ip_prefix[1]}"

            local num_ips=$((2**(32 - prefix)))
            ip_int=$(ip_to_int "$ip")

            # Calculate the network address and broadcast address
            network_address=$((ip_int & ~(num_ips - 1)))
            broadcast_address=$((network_address + num_ips - 1))

            for ((ip_num = network_address + 1; ip_num < broadcast_address; ip_num++)); do
                echo "$(int_to_ip "$ip_num")"
            done
        else
            echo "$range"
        fi
    done
}

# Function to scan hosts for open ports using TCP/UDP
scan_hosts() {
    local target="$1"
    local protocol="$2"
    shift 2
    local ports=("$@")

    local target_list=()
    IFS=$'\n' read -rd '' -a target_list < <(expand_ip_range "$target")

    local valid_ports=()
    local invalid_ports=()

    for port in "${ports[@]}"; do
        if ! [[ "$port" =~ ^[0-9]+$ ]] || ((port < 1 || port > 65535)); then
            invalid_ports+=("$port")
        else
            valid_ports+=("$port")
        fi
    done

    if [ ${#invalid_ports[@]} -gt 0 ]; then
        print_message "WRN" "Invalid ports, will not be used for check: ${color_map[FAL]}${invalid_ports[*]}${NC}"
    fi

    # Perform scanning for valid ports
    for target in "${target_list[@]}"; do
        for port in "${valid_ports[@]}"; do
            if [ "$protocol" = "UDP" ]; then
                if nc -zu -w1 "$target" "$port" >/dev/null 2>&1; then
                    print_message "INF" "Open $protocol port $target:$port"
                else
                    print_message "INF" "Closed or filtered $protocol port $target:$port"
                fi
            else
                # Check if the port is open using a headless connection attempt (TCP)
                if timeout 1 bash -c "echo >/dev/tcp/$target/$port" >/dev/null 2>&1; then
                    print_message "INF" "Open $protocol port $target:$port"
                else
                    print_message "INF" "Closed $protocol port $target:$port"
                fi
            fi
        done
    done
}


function title() {
    emojis=('🌴' '⛺️ ' '🛶' '🌿' '🌲' '🌳' '🌊' '🦌' '🌺' '🦋')
    shuffled_emojis=($(shuf -e "${emojis[@]}")) 
    # Get the current hour (24-hour format)
    current_hour=$(date +%H)
    # Set the dark mode if the time is between 10:00 pm and 07:00 am
    if (( current_hour >= 22 || current_hour < 7 )); then
        # Dark mode
        local title_mod="BOLD_GREEN_ON_BLACK"
        local paragraph_mod="WHITE_ON_DARK"
    else
        # White mode
        local title_mod="BOLD_GREEN_ON_WHITE"
        local paragraph_mod="BLACK_ON_WHITE"
    fi
    # echo -e "${color_map[On_Black]}                                 \n       Living off the land       \n       Network scaner ${shuffled_emojis[0]}         \n                                 ${NC}"
    echo -e "\n${color_map[$title_mod]}                                  "
    echo -e "       lolnetscan $lolnetscan_version              ${NC}${color_map[$paragraph_mod]}"
    echo -e "                                  "
    echo -e "       Living off the land        "
    echo -e "       Headless bash Network      "
    echo -e "       Scanner ${shuffled_emojis[0]}                 "
    echo -e "                                  \n${NC}"
}
# Main function to parse command-line arguments and initiate scanning
main() {
    local target=""
    local ports=()
    local use_udp=false

    while [[ $# -gt 0 ]]; do
        case $1 in
            -host)
                shift
                target="$1"
                shift
                ;;
            -u)
                use_udp=true
                shift
                ;;
            -p)
                shift
                IFS=',' read -ra input_ports <<< "$1"
                ports=($(validate_ports "${input_ports[@]}"))
                shift
                ;;
            -v)
                echo "$lolnetscan_version"
                ;;
            *)
                print_message "FAL" "Error: Invalid option or value: $1"
                print_usage
                ;;
        esac
    done

check_os
check_dependencies

    if [ -z "$target" ]; then
        print_message "FAL" "Error: Missing required option(s)."
        print_usage
        exit 1
    fi
    title

    if [ ${#ports[@]} -eq 0 ]; then
        if [ "$use_udp" = true ]; then
            print_message "FAL" "Option -u can be used only if -p provided followed by port(s)"
            print_usage
        fi
        # No ports specified, only check for live hosts
        for target_ip in $(expand_ip_range "$target"); do
            if ping -c 1 -W 1 "$target_ip" >/dev/null 2>&1; then
                print_message "INF" "Host $target_ip is ${color_map[GREEN]}alive${NC}"
            else
                print_message "INF" "Host $target_ip is ${color_map[RED]}down${NC}"
            fi
        done
    else
        if [ "$use_udp" = true ]; then
            if ! command -v nc &>/dev/null; then
                print_message "INF" "UDP port scanning requires the 'nc' (netcat) tool."
                print_message "USG" "apt-get install -y --no-install-recommends netcat"
            fi
            print_message "INF" "Using tool 'nc' (netcat) for UDP port check"
            scan_hosts "$target" "UDP" "${ports[@]}"
        else
            scan_hosts "$target" "TCP" "${ports[@]}"
        fi
    fi
}
main "$@"
